pipeline {
    agent any
    
    environment {
        TOMCAT_USER = 'admin'  // Update with your Tomcat user
        TOMCAT_PASSWORD = 'admin'  // Update with your Tomcat password
        TOMCAT_URL = 'http://100.27.230.167:8080'  // Update with your Tomcat URL
        WAR_FILE = 'target/*.war'  // Update with your WAR file name
    }

    stages {
        stage('Checkout Code') {
            steps {
               
                echo "passed"
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package -DskipTests'  // Skip tests if needed
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'tomcat-credentials', usernameVariable: 'TOMCAT_USER', passwordVariable: 'TOMCAT_PASSWORD')]) {
                        sh """
                            curl -u $TOMCAT_USER:$TOMCAT_PASSWORD --upload-file $WAR_FILE $TOMCAT_URL/manager/text/deploy?path=/your-app&update=true
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Deployment Failed!'
        }
    }
}
