pipeline {
    agent {
        any
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'echo passed'
                git branch: 'main', url: 'https://github.com/Hemalatha0411/Jenkins-CI-CD.git'
            }
        }
        stage('Build and Test') {
            steps {
                sh 'ls -ltr'
                /* build the project and create a JAR file */
                sh 'cd java-maven-k8s/spring-boot-app && mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                /* deploy war on tomcat server */
                deploy adapters: [tomcat9(url: 'http://18.207.115.70:8080/', credentialsId: 'tomcat-credentials')], war: 'target/*.war', contextPath: 'pipeline-app'
            }
        }
    }
}
